---
auths:
  public_v1:
    version: 1
  public_v2:
    version: 2

modules:
  # SNMPv2-MIB for things like sysDescr, sysUpTime, etc.
  system:
    walk:
      # - "SNMPv2-MIB::system"
      - sysName
      - sysUpTime
      - interfaces
      - ifXTable
      - ifHCInOctets
      - ifHCOutOctets
      - ifInErrors
      - ifOutErrors
    lookups:
      - source_indexes: [sysORIndex]
        lookup: "SNMPv2-MIB::sysORDescr"
  # Default IF-MIB interfaces table with ifIndex.
  if_mib:
    walk:
      - sysName
      - sysUpTime
      - "IF-MIB::interfaces"
      - "IF-MIB::ifXTable"
      - ifHCInOctets
      - ifHCOutOctets
      - ifInErrors
      - ifOutErrors
    lookups:
      - source_indexes: [ifIndex]
        lookup: "IF-MIB::ifAlias"
      - source_indexes: [ifIndex]
        # Disambiguate from PaloAlto PAN-COMMON-MIB::ifDescr.
        lookup: "IF-MIB::ifDescr"
      - source_indexes: [ifIndex]
        # Disambiguate from Netscaler NS-ROOT-MIB::ifName.
        lookup: "IF-MIB::ifName"
    overrides:
      ifAlias:
        ignore: true # Lookup metric
      ifDescr:
        ignore: true # Lookup metric
      ifName:
        ignore: true # Lookup metric
      ifType:
        type: EnumAsInfo
  # Default IP-MIB with ipv4InterfaceTable for example.



