version: "3.8"

services:
  janus:
    container_name: janus
    image: swmansion/janus-gateway:1.2.3-0
    environment:
      - WEBSOCKETS_ENABLED=true
      - WEBSOCKETS_INTERFACE=eth0
      - DEBUG_LEVEL=7
      - GATEWAY_IP=${JANUS_GATEWAY_IP}

    # volumes:
    #   - ./janus:/usr/local/etc/janus
    #   # - ./share:/usr/local/share/janus

    ports:
      - "8088:8088"     # Janus HTTP API
      - "8188:8188"     # Janus WebSocket API
      # - "10000-10100:10000-10100/udp"  # Media
    networks:
      - janus-net

  nginx:
    image: nginx:alpine
    container_name: nginx

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/usr/share/nginx/html
      - ./certs:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - janus
    networks:
      - janus-net

  asterisk:
    image: andrius/asterisk:latest
    container_name: asterisk
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      # - "10000-10100:10000-10100/udp"
    volumes:
      - ./asterisk/pjsip.conf:/etc/asterisk/pjsip.conf
      - ./asterisk/extensions.conf:/etc/asterisk/extensions.conf
    restart: unless-stopped
    networks:
      - janus-net


networks:
  janus-net:
    driver: bridge
