services:

  grafana:
    image: grafana/grafana
    env_file:
      - env/.env.grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    # environment:
    #   - GF_SECURITY_ADMIN_USER=admin
    #   - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      # - ./mnt/grafana-data:/var/lib/grafana
      - grafana_data:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    env_file:
      - env/.env.prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      # - ./mnt/prometheus-data:/prometheus
      - prom_data:/prometheus

  snmp_exporter:
    image: prom/snmp-exporter:v0.26.0
    container_name: snmp_exporter
    command:
      - '--config.file=/etc/snmp_exporter/snmp.yml'
    restart: unless-stopped
    volumes:
      - ./snmp/:/etc/snmp_exporter/
    ports:
      - "9116:9116"
      - "161:161/udp"
    depends_on:
      - prometheus
      
volumes:
  prom_data:
  grafana_data:




    